### ISSUE TITLE
Can not install ES3SaveHook

### ISSUE THREAD

**Issue by Cicini** [Henry1887/BepInEx-AutoInstaller#1]
It looks like ES3SaveHook is no longer available, and I can't find anywhere on the Web to download it.

**Comment by Yana-Hoshino** [comment]
Did you find any links? same problem

**Comment by ZeyuanGuo** [comment]
same

**Comment by Henry1887** [comment]
The ES3SaveHook Plugin was hosted on discords cdn and its not available anymore. I'll update this sometime in the future with a new working ES3SaveHook Plugin.
