### ISSUE TITLE
The Download Link are invalid.

### ISSUE THREAD

**Issue by Qihoysa** [Henry1887/BepInEx-AutoInstaller#2]
Thanks for you code.
But the address in list 'links', "ES3SAVEHOOKIL2CPP" and "ES3SAVEHOOK" are invalid.
And I can't get them from google or any website, do you have backup? Thank you so mach.

**Comment by Henry1887** [comment]
Hello,

the ES3SaveHook Links are for a outdated plugin for obtaining the decryption key from Unity Games that are using EasySave3 to encrypt their save files. There are better methods available and thats why havent updated the links. I have written a complete guide for it here: https://f95zone.to/threads/how-to-edit-decrypt-easysave-3-es3-save-files.165329/
